name = "KMATools"
uuid = "f2dc44fa-c02b-42d6-8c22-04adf9d07357"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
version = "0.1.1"

[deps]
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
